### PR TITLE
Add stateA, readerA, writerA

### PR DESCRIPTION
**Pull request by k0001**
Somewhat following the conversation in #4, I decided to send a pull-request adding `stateA`. While I was at it, I figured adding similar support for `ReaderT` and `WriterT` which are already on the library would be welcome too. 

Using `stateA`:

```
> streamAuto (sealState (stateA (arr (\(a,s) -> ((a*s), s*10)))) 1) [1..5]
[1,20,300,4000,50000]
```

Using `readerA`:

```
> streamAuto (sealReader (readerA (arr (\(a,r) -> a*r))) 10) [1..5]
[10,20,30,40,50]
```

Using `writerA`:

```
> runWriterT (streamAuto (writerA (arr (\a -> (a, [a*10])))) [1..5])
([1,2,3,4,5],[10,20,30,40,50])
```

I should point out that [`Pipes.Lift`](https://hackage.haskell.org/package/pipes-4.1.4/docs/Pipes-Lift.html) from the `pipes` library provides similar tools, and in my experience using `pipes` they've proven to be quite handy.

### CODE REVIEW

**Comment by k0001** [comment]
I should add that I'm a bit confused about the choice of the lazy `WriteT` and `StateT` instead of their strict variants. Could you comment on this choice? I'm inclined to think that a strict `StateT` is the best choice in most scenarios, as otherwise lazy accumulators such as these often become significant space leaks. 

Almost the same applies to `WriterT`, except the accumulator is a monoid. Unfortunately the current strict implementation of `WriterT` is not as strict as it should be. [`Pipes.Lift`](https://hackage.haskell.org/package/pipes-4.1.4/docs/Pipes-Lift.html#g:6) gives a hint on how to deal with that.

**Comment by k0001** [comment]
Then, having `stateA`, we can easily create something like the `evalAccum` I mentioned in #4, but compatible with `sealState`:

``` haskell
accumA
  :: Monad m
  => Auto m (a, b) b
  -> Auto (StateT b m) a b
accumA au = stateA (arr (\x -> (x,x)) . au)
```

I think this function is particularly useful as it allows you to not think of manually manipulating the state within `Auto m (a, b) b`,  just like when using `accum` or `accumM`. I'm already making use of `accumA` in some code here and enjoying it quite much :)

**Comment by mstksg** [comment]
Regarding Lazy vs Strict Writer/StateT: The choice wasn't a conscious one, I just forgot to add `Strict` to the imports :)  I think switching to Strict and Lazy would be for the best.  Though it will be a breaking change, it's one that the compiler can catch so, I am not too hesitant in putting it into the `0.3` release.

That being said I'd have to test it out with some usages of `ArrowLoop` because strict bindings can lead to knot-tying problems with recursive bindings.

**Comment by mstksg** [comment]
I can see this being a useful way to write things that you intend to write over `StateT s m`, without explicitly fiddling with `effect` and `arrM`....once in `StateT` form, you can compose it, etc....so I can definitely see its usage.

`writerA` and `readerA` I am on board with.  I'm slightly hesitant with `stateA` because making `StateT` so easy to "get into" might accidentally encourage code that's difficult to maintain or reason able (I've never had a real occasion to use `StateT` other than its limited `RandT` counterpart for randomness).  But I guess if we add in `writerA` and `readerA`, then `stateA` might as well be thrown in for completeness.

I'll probably just put some warnings in the documentation, then :)

Thanks for the work and suggestions!  Really appreciated. :)

**Comment by mstksg** [comment]
A little embarrassing, but my test coverage didn't point out that using strict state and writer prevents _auto_ from tying knots for recursive bindings.  so change to strict state/writer has been reverted for 0.4 :)

**Comment by k0001** [comment]
Oh! How unfortunate. Well, I'm glad you noticed this so fast, hopefully no
harm was done. Thank you for sharing.
Il 04/apr/2015 01:38, "Justin Le" notifications@github.com ha scritto:

**Comment by mstksg** [comment]
Yeah, it's rather unfortunate.  Extra strictness has been a big pain during the whole implementation process and at the lowest level there were some "free performance" increasing methods that had to have been scrapped (the performance is still recoverable but explicitly, not implicitly) in the name of recursive bindings.  Perhaps it'll be worth adding in strict Writer and State in the future for use in the cases where you don't have any recursive bindings :)

**Pull request merged**
